type: object
properties:
  href:
    type: string
  Parent:
    $ref: "#/components/schemas/HyperReference"
  AssignableResource:
    $ref: "#/components/schemas/HyperReference"
  OccupancySensorSettings:
    $ref: "#/components/schemas/OccupancySensorSettingsUpdate"
