import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";
import { classifyRoutes } from "../lib/site/uncovered.ts";

/**
 * Regenerate the unverified import allowlist. The list is committed rather
 * than derived at bundle time so that what the document asserts is auditable
 * in review, and so a change to the classifier shows up as a diff.
 */
if (process.argv[1]?.endsWith("derive-unverified.ts")) {
  const doc = parse(readFileSync("dist/openapi.yaml", "utf8")) as {
    paths: Record<string, Record<string, unknown>>;
  };
  // Classify against the refined tree alone. The bundle already carries the
  // previous import, and counting those as covered would derive an empty list.
  const refined = new Set(
    Object.entries(doc.paths)
      .filter(([, item]) => item["x-leap-verified"] !== false)
      .map(([path]) => path),
  );
  const paths = classifyRoutes({ bundledPaths: refined })
    .filter((route) => route.absence === "uncovered")
    .map((route) => route.path)
    .sort();

  writeFileSync(
    "spec/unverified-paths.json",
    `${JSON.stringify(
      {
        note:
          "Firmware route templates imported without hand-refinement. " +
          "Generated by tools/derive-unverified.ts from the face-value " +
          "classification in lib/site/uncovered.ts; committed so the import " +
          "set is auditable and drift is visible. See README.",
        paths,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  console.log(`wrote ${paths.length} unverified paths`);
}
